// <auto-generated />
using CatalogService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CatalogService.Infrastructure.Migrations
{
    [DbContext(typeof(EfCatalogServiceDbContext))]
    [Migration("20251023064244_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CatalogService.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UnitsInStock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "12 Parça Porselen Tabak Seti",
                            IsActive = true,
                            Name = "Tabak Seti",
                            Price = 1000.00m,
                            UnitsInStock = 100
                        },
                        new
                        {
                            Id = 2,
                            Description = "6 Parça Fincan Seti",
                            IsActive = true,
                            Name = "Kahve Fincanı",
                            Price = 799.99m,
                            UnitsInStock = 50
                        },
                        new
                        {
                            Id = 3,
                            Description = "3 Programlı Bulaşık Makinesi",
                            IsActive = true,
                            Name = "Bulaşık Makinesi",
                            Price = 8000.00m,
                            UnitsInStock = 20
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
